const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#F5F5FF",
    foreground: "#0a0a1a",
    card: "#FFFFFF",
    cardForeground: "#0a0a1a",
    primary: "#7C3AED",
    primaryForeground: "#ffffff",
    secondary: "#F0F0F8",
    secondaryForeground: "#4B4B6B",
    muted: "#F0F0F8",
    mutedForeground: "#6B7280",
    accent: "#7C3AED",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#E2E2F0",
    input: "#F0F0F8",
  },
  dark: {
    text: "#0a0a0a",
    tint: "#8B5CF6",
    background: "#080811",
    foreground: "#EEEEFF",
    card: "#0F0F1C",
    cardForeground: "#EEEEFF",
    primary: "#8B5CF6",
    primaryForeground: "#ffffff",
    secondary: "#1A1A2E",
    secondaryForeground: "#AAAACC",
    muted: "#1A1A2E",
    mutedForeground: "#6B7280",
    accent: "#8B5CF6",
    accentForeground: "#ffffff",
    destructive: "#EF4444",
    destructiveForeground: "#ffffff",
    border: "#252540",
    input: "#1A1A2E",
  },
  radius: 14,

  characters: {
    larry: "#8B5CF6",
    sensei: "#F59E0B",
    "dr-neo": "#3B82F6",
    hassan: "#10B981",
  },
};

export default colors;
